### ISSUE TITLE
keep jade in your dependency and specify jade version in package.json

### ISSUE THREAD

**Issue by postor** [kurohara/phpjade#2]
consider it

**Comment by kurohara** [comment]
Yes you are right.  
I have to provide the way to check the version of Jade.  
But Jade module is applied outside of phpjade, so I'm considering the way how to specify the version of jade other than 'dependency' value in package.json.  
(I don't want to pull the Jade module under phpjade)  
https://github.com/kurohara/jade-php/wiki  see bottom line.

**Comment by postor** [comment]
once you fix the problem with versions of jade, inform me please, for i'm depending on u, and now the versions are limited in my packages.json
https://github.com/postor/gulp-phpjade

**Comment by kurohara** [comment]
OK, I would.
But if you don't feel bother, try to set 'watch' state to this repository so that you will receive update notification automatically.
Thank you for having interest to this code.
